require: rubocop-rspec
require: rubocop-performance
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'bin/*'
    - 'app/channels/**/*'
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Encoding:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 30
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Rails:
  Enabled: true
