require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'app/channels/**/*'
    - 'vendor/**/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'

Style/Encoding:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/users/omniauth_callbacks_controller.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/initializers/simple_form.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/features/**/*'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/environments/*'

Documentation:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'

RSpec/MultipleExpectations:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true
