require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'app/channels/**/*'
    - 'vendor/**/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/initializers/simple_form.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/features/**/*'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/environments/production.rb'
    - 'config/environments/development.rb'

Documentation:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/*/**'
RSpec/DescribeClass:
  Exclude:
    - 'spec/features/*/**'
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/*/**'

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true
