require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'app/channels/**/*'
    - 'vendor/**/*'
    - config/initializers/simple_form_bootstrap.rb
    - config/application.rb

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 160

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'configure']
  Max: 30

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3

RSpec/DescribeClass:
  Enabled: false
