AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'bin/*'
    - 'app/channels/**/*'
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Encoding:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 125
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 30
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
