version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:10.8-alpine
        environment:
          POSTGRES_USER: kolya
          POSTGRES_PASSWORD: 'qwerty123'
          POSTGRES_DB: bookstore_test
          DATABASE_URL: "postgres://ubuntu@localhost:5432/bookstore_test"
    steps:
      - checkout
      - run:
          name: Install Chrome
          command: |
            sudo apt-get install libxss1 libappindicator1 libindicator7
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i ./google-chrome*.deb
            sudo apt-get install -f
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ")
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $TEST_FILES
      - run:
          name: run rubopcop
          command: bundle exec rubocop


      - store_test_results:
          path: /tmp/test-results
