default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= Rails.application.credentials[:db][:username] %>
  password: <%= Rails.application.credentials[:db][:password] %>
  port: 5432
  pool: 5

development:
  <<: *default
  host: localhost
  database: bookstore_develop

production:
  <<: *default
  database: bookstore_production

test:
  <<: *default
  host: localhost
  username: rails_dev
  database: bookstore_test
