default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= Rails.application.credentials[:aws][:username] %>
  password: <%= Rails.application.credentials[:aws][:password] %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: bookstore_develop

production:
  <<: *default
  database: bookstore_production

test:
  <<: *default
  database: bookstore_test
