default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: kolya
  password: 'qwerty123'
  port: 5432
  pool: 5

development:
  <<: *default
  database: bookstore_develop

production:
  <<: *default
  database: bookstore

test:
  <<: *default
  database: bookstore_test
