default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= Rails.application.credentials[:db][:username] %>
  password: <%= Rails.application.credentials[:db][:password] %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: bookstore_develop

production:
  <<: *default
  database: bookstore_production

test:
  <<: *default
  host: <%= ENV['CIRCLECI'] ? 'localhost' : 'db' %>
  username: <%= ENV['CIRCLECI'] ? 'rails_dev' : Rails.application.credentials[:db][:username] %>
  database: bookstore_test
