version: '3'

volumes:
  assets:

services:
  web_server:
    image: 046546929238.dkr.ecr.us-east-1.amazonaws.com/bookstore/web_server:staging
    volumes:
      - assets:/home/www/spreedemo/public/assets
    environment:
      STATIC_PATH: /home/www/spreedemo/public
    ports:
      - 80:8080
    links:
      - server_app
    logging:
      driver: awslogs
      options:
        awslogs-group: bookstore-staging
        awslogs-region: us-east-1
        awslogs-stream-prefix: web_server
    healthcheck:
      test: ["CMD-SHELL", "service nginx status || exit 1"]

  server_app: &server_app
    image: 046546929238.dkr.ecr.us-east-1.amazonaws.com/bookstore/server_app:staging
    command: bundle exec puma -C config/puma.rb
    entrypoint: "./docker-entrypoint.sh"
    ports:
      - 3000
    environment:
      RAILS_ENV: staging
      RAILS_MASTER_KEY: 464b85ba33f01424e77b37e07dc900a6
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bookstore_staging
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - assets:/home/www/bookstore/public/assets
    links:
      - db
    logging:
      driver: awslogs
      options:
        awslogs-group: bookstore-staging
        awslogs-region: us-east-1
        awslogs-stream-prefix: server_app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]

  db:
    image: postgres:10
    environment:
      POSTGRES_DB: bookstore_staging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    volumes:
      - /postgres:/var/lib/postgresql/data
    logging:
      driver: awslogs
      options:
        awslogs-group: bookstore-staging
        awslogs-region: us-east-1
        awslogs-stream-prefix: db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
